name: Build and Push asrm-web

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare lowercase image name
        id: vars
        run: |
          echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT
          echo "REPO_LC=${GITHUB_REPOSITORY##*/}" >> $GITHUB_OUTPUT
          echo "REPO_LC=${REPO_LC,,}" >> $GITHUB_OUTPUT
          echo "IMAGE=ghcr.io/${GITHUB_REPOSITORY_OWNER,,}/asrm-web" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ steps.vars.outputs.IMAGE }}:latest
            ${{ steps.vars.outputs.IMAGE }}:${{ github.sha }}

